### ISSUE TITLE
🎃  Hacktoberfest:  Extend web browsing in the developer toolkit to support multiple browser engines beyond Chromium (e.g., Firefox, WebKit)

### ISSUE THREAD

**Issue by blackgirlbytes** [block/goose#170]
# 🎃 Hacktoberfest: Extend Developer Toolkit Web Browsing

### 📝 Description
The [Developer toolkit](https://github.com/block-open-source/goose/blob/main/src/goose/toolkit/developer.py) currently supports web browsing via the `fetch_web_content` method, but it's limited to Chromium. We need to expand this to support Firefox and WebKit for improved versatility and compatibility.

### 🎯 Objective
Enhance `fetch_web_content` to allow users to choose between Chromium, Firefox, and WebKit for web content fetching.

### 🛠️ Implementation Steps
1. Update `fetch_web_content` to accept a browser option
2. Implement browser selection logic using Playwright
3. Add error handling for unsupported browser options
4. Update documentation for new browser options
5. Extend test suite to cover all supported browsers

### ✨ Key Features
- Support for Chromium, Firefox, and WebKit
- User-specifiable browser preference
- Fallback mechanism for unavailable browsers
- Consistent content fetching across browsers

### 🚀 Getting Started
1. Fork the repository
2. Review the [documentation](https://block-open-source.github.io/goose)
3. Locate `fetch_web_content` in the [Developer toolkit](https://github.com/block-open-source/goose/blob/main/src/goose/toolkit/developer.py)
4. Implement browser selection logic
5. Add tests for Firefox and WebKit
6. Update toolkit documentation

#### Prerequisites
- [uv](https://github.com/astral-sh/uv) for dependency management
- [ruff](https://github.com/astral-sh/ruff) for formatting
- [just](https://github.com/casey/just) for command shortcuts (optional)

#### Setup
1. Clone Goose repository
2. Install `uv`
3. Run `uv` in your local Goose directory to set up the virtualenv and install dependencies

#### Development Commands
- Run Goose: `uv run goose session start`
- Run tests: `uv run pytest tests -m "not integration"` or `just test`
- Create dev alias: `alias goosedev=\`uv run which goose\``

### 📚 Example Usage
After implementation:
```python
content_path = toolkit.fetch_web_content(url, browser_name="firefox")
```

### 🧪 Testing Checklist
- [ ] Content fetching with each supported browser
- [ ] Handling of unsupported browser options
- [ ] Fallback behavior for unavailable browsers

### 📘 Documentation Updates
- [ ] Browser specification instructions
- [ ] Browser-specific considerations/limitations

We welcome contributions of all levels. If you have questions, please ask in the comments!
